apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    app: blue
spec:
  selector:
    matchLabels:
      app: blue
    spec:
      containers:
        - name: blue
          image: muzammilkazmi86/greenblue
          ports:
            - containerPort: 8080
