apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
spec:
  selector:
    matchLabels:
      app: blue
  replicas: 3
  template:
    metadata:
      labels:
        app: blue
    spec:
      containers:
        - name: blue
          image: muzammilkazmi86/greenblue
          ports:
            - containerPort: 8080
