---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-demo-cluster
  region: us-east-2
nodeGroups:
  - name: my-demo-workers
    instanceType: t2.micro
    desiredCapacity: 4
    minSize: 1
    maxSize: 4
