apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
spec:
  selector:
    matchLabels:
      app: green
  replicas: 3
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: muzammilkazmi86/greenblue
          ports:
            - containerPort: 8080
