apiVersion: apps/v1
kind: Deployment
metadata:
  name: green
  labels:
    app: green
spec:
  selector:
    matchLabels:
      app: green
    spec:
      containers:
        - name: green
          image: muzammilkazmi86/greenblue
          ports:
            - containerPort: 8080
