apiVersion: v1
kind: ReplicationController
metadata:
  name: green
  labels:
    app: green
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
        - name: green
          image: muzammilkazmi86/greenblue
          ports:
            - containerPort: 8080
